### ISSUE TITLE
[LXN10007] Cannot decode some CR2 files

### ISSUE THREAD

**Issue by mauritiusdadd** [mauritiusdadd/lxnstack#7]
When trying to decode a CR2 file generated by a Canon EOS 400D, the following exception is raised:

``` python
ERROR: KeyError: 273 [cr2plugin]
 Traceback (most recent call last):
   File "/usr/share/lxnstack/main_app.py", line 1195, in doLoadFiles
     self.loadFiles()
   File "/usr/share/lxnstack/main_app.py", line 3042, in loadFiles
     ref = utils.Frame(str(newlist[0]), **self.frame_open_args)
   File "/usr/share/lxnstack/utils.py", line 416, in __init__
     _tmp_data = self.open(self.url, page, PIL_priority=True,
 only_sizes=True, **args)
   File "/usr/share/lxnstack/utils.py", line 480, in open
     only_sizes, force_update, **args)
   File "/usr/share/lxnstack/utils.py", line 727, in _open
     cr2file = cr2plugin.imread(file_name)
   File "/usr/share/lxnstack/cr2plugin.py", line 1106, in imread
     cr2img=QCR2Image(fname)
   File "/usr/share/lxnstack/cr2plugin.py", line 485, in __init__
     self.open()
   File "/usr/share/lxnstack/cr2plugin.py", line 604, in open
     self.CR2SLICES = (self.IFD3[StripOffset],
 KeyError: 273
```

**Comment by mauritiusdadd** [comment]
fixed in version 1.4.4
