### ISSUE TITLE
[LXN10008] Sometimes the program hangs while searching for hot pixels.

### ISSUE THREAD

**Issue by mauritiusdadd** [mauritiusdadd/lxnstack#8]
Sometimes the program hangs while searching for hot pixels.
The following backtrace can be obtained by stopping the program manually with Ctrl-c in the console:

``` python
ERROR: KeyboardInterrupt [numpy.core.numeric]
Traceback (most recent call last):
  File "/usr/share/lxnstack/main_app.py", line 5165, in doStack self.stack()
  File "/usr/share/lxnstack/main_app.py", line 5315, in stack_stk=self.getStackingMethod(lght_method,self.framelist, self._bas, self._drk, self._flt,**lght_args)
  File "/usr/share/lxnstack/main_app.py", line 5143, in getStackingMethod return self.average(framelist, bias_image, dark_image, flat_image, **args)
  File "/usr/share/lxnstack/main_app.py", line 5740, in average post_operation = np.divide, **args)
  File "/usr/share/lxnstack/main_app.py", line 5493, in nativeOperationOnImages master_bias, master_dark, master_flat, hot_pixels = self.generateMasters(bias_image,dark_image,flat_image)
  File "/usr/share/lxnstack/main_app.py", line 5371, in generateMasters hot_pixels=np.argwhere((master_dark-dmin)>n*fac)            
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 629, in argwhere return transpose(asanyarray(a).nonzero())
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 487, in transpose return _wrapit(a, 'transpose', axes)
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 38, in _wrapit result = getattr(asarray(obj),method)(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 320, in asarray return array(a, dtype, copy=False, order=order)

KeyboardInterrupt
ERROR: KeyboardInterrupt [main_app]
Traceback (most recent call last):
  File "/usr/share/lxnstack/main_app.py", line 2221, in colorBarPaintEvent def colorBarPaintEvent(self, obj):
KeyboardInterrupt
```

**Comment by mauritiusdadd** [comment]
Fix will be released in version 1.5.0
